M48
; DRILL file {KiCad 7.0.5} date Sun Jul 23 10:45:43 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-23T10:45:43+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.400
%
G90
G05
T1
X45.31Y-71.27
X64.39Y-38.963
T2
X38.31Y-31.963
X38.31Y-71.27
X64.39Y-31.963
X64.39Y-71.27
T0
M30
